name: "research"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm git meson clang glslang libcap wlroots \
            sdl2 vulkan-headers libx11 libxmu libxcomposite libxrender libxres \
            libxtst libxkbcommon libdrm libinput wayland-protocols benchmark \
            xorg-xwayland pipewire cmake \
            libavif libheif aom rav1e libdecor libxdamage

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: c-cpp
          queries: security-extended,security-and-quality

      - name: Build with clang
        run: |
          export CC=clang CXX=clang++
          meson build-clang/ -Dinput_emulation=disabled --werror --auto-features=enabled
          ninja -C build-clang/

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:c-cpp"
